### ISSUE TITLE
Sorting table bugs

### ISSUE THREAD

**Issue by shellajt** [Ledger-Software/Ledger#129]
Sorting the by the amount column uses a string based sort instead of numerical.

Sorting by Payee also doesn't work. I'm not sure exactly what it's doing.

Sorting by Type also doesn't work. Not sure what goes wrong, but it doesn't even group the types together.

**Comment by taylerhow** [comment]
Functionality to sort by Amount, Payee, and Type was corrected in PR #135. Sorting for Date & Cleared is working as intended. The team was discussing disabling the ability to sort by Categories, because there isn't an intuitive ordering system for them.

**Comment by shellajt** [comment]
Resolved
