### ISSUE TITLE
Inconsistent balance calculations

### ISSUE THREAD

**Issue by shellajt** [Ledger-Software/Ledger#174]
We calculate the amount spent in the account balance label and in the spending charts. The values do not seem to match.

![image](https://cloud.githubusercontent.com/assets/11395587/22796147/4625e704-eec7-11e6-8750-a953a60cbb33.png)

**Comment by LadyMopar** [comment]
We need to discuss this. I don't believe the account balance label should reflect what's in the expenditure charts. Account balance is how much $$ is in the account after deposits and expenditures. Expenditures page only takes into consideration expenditures, not the current status of the account as a whole.

**Comment by shellajt** [comment]
I agree, but the math doesn't seem to add up. Certainly a possibility that I cant add though....

**Comment by LadyMopar** [comment]
If it helps, the expenditure history chart takes into consideration both deposits and expenditures to show the change in account balance each month. The pie chart is based solely off of expenditures - it ignores all deposits. We can change what each chart is supposed to represent at some point, but at the moment that's how they work.

**Comment by taylerhow** [comment]
I think the pie chart should account for deposits somehow, maybe just in a "Deposits" portion of the pie?

**Comment by shellajt** [comment]
Addressed in PR #243
