### ISSUE TITLE
TableView filtering on hidden column?

### ISSUE THREAD

**Issue by taylerhow** [Ledger-Software/Ledger#205]
Currently, using the search bar on the transaction tableview filters transactions by searching Amount, Payee name, Tag names, Check Number, and Account name for the specified filter string. This implementation includes hidden columns in the possible filter matches (if you hide the check number column, and search for 1234, any transactions with check number = 1234 will still show up in the filtered data set, it just may not be immediately apparent why). It's a potentially confusing scenario as the user may not know when certain transactions are showing up in the filtered data set. Do we want to disable filtering for hidden columns, or just leave it in?

**Comment by shellajt** [comment]
Discussed this during standup March 8. Decided that hidden columns should not affect the filter

**Comment by taylerhow** [comment]
Filtering mechanics updated in PR #241, pending peer review.

**Comment by taylerhow** [comment]
PR #241 merged. Filtering has been updated to include all columns except the Date & Cleared columns, and ignore all hidden columns.

**Comment by taylerhow** [comment]
Whoops, maybe we should wait for Sean's review before closing this (?)

**Comment by taylerhow** [comment]
Table view filter also does not include the Note column. Should it?

**Comment by shellajt** [comment]
I don't think we need to wait for Sean's review. Does he even know this change is happening?

I don't think we need to search the note column. Probably not a lot of search worthy information there
