### ISSUE TITLE
Mac UI Issue (Left hand bar scrolling)

### ISSUE THREAD

**Issue by SeanFromIT** [Ledger-Software/Ledger#238]
If all three sections are open, the balance window cannot be scrolled to. 
![image](https://cloud.githubusercontent.com/assets/10387753/24211320/06b7db3a-0f02-11e7-8f9e-d43f8f035b4a.png)

**Comment by shellajt** [comment]
Possible duplicate of issue #230.

**Comment by taylerhow** [comment]
Just tested on my Mac with 1280x800 resolution. Looks like it's been fixed.
