### ISSUE TITLE
TODOs in ImportTransactionsPopupController

### ISSUE THREAD

**Issue by shellajt** [Ledger-Software/Ledger#259]
We have a couple TODOs in this file. I'm not sure what they mean.

![image](https://cloud.githubusercontent.com/assets/11395587/25239965/a067ca8c-25bf-11e7-8140-8702d1aa027a.png)

![image](https://cloud.githubusercontent.com/assets/11395587/25239991/b3f23600-25bf-11e7-9235-455f971002c6.png)

Looks like @cjm721 wrote both.

**Comment by cjm721** [comment]
The second one we don't really do anything with transactions that cause an exception (we just ignore them)

The first I think settings the onAction for the importButton is what I meant and just never deleted it.
