### ISSUE TITLE
Changing Type in Add Transaction Window Makes Selected Account Blank

### ISSUE THREAD

**Issue by LadyMopar** [Ledger-Software/Ledger#275]
While filling out the information in the Add Transaction window, if you select an account before a type, changing the type will make the account field go blank and you have to re-select it.
![image](https://cloud.githubusercontent.com/assets/10874723/25719190/93122644-30d6-11e7-9086-cefee9f32a8a.png) ===>>>
![image](https://cloud.githubusercontent.com/assets/10874723/25719203/a3fa8b72-30d6-11e7-849f-1a37de4fd543.png)

**Comment by taylerhow** [comment]
Resolved in PR #296
