### ISSUE TITLE
Can't Add Any Transactions Besides Transfer (transfer bug)

### ISSUE THREAD

**Issue by LadyMopar** [Ledger-Software/Ledger#276]
We can't add any other type of transaction besides a transfer because an error popup will show up complaining about accounts must be different for transfers. This blocks any sort of transaction from being added manually. I tried every single type and this happens for all except transfer.
![image](https://cloud.githubusercontent.com/assets/10874723/25719461/95312bb8-30d7-11e7-9d49-7f9c2dbf120f.png)

Importing still works fine.

**Comment by shellajt** [comment]
Getting the same thing
