### ISSUE TITLE
Type Verification incorrect when adding transaction

### ISSUE THREAD

**Issue by shellajt** [Ledger-Software/Ledger#286]
For example, theres no reason you cannot receive cash or a check, but we force those types to negative amounts.

![image](https://cloud.githubusercontent.com/assets/11395587/25754617/e73abefe-318d-11e7-91c2-02e2f966de7a.png)

**Comment by taylerhow** [comment]
Spent a little time thinking about this.. if you receive a check from another person and deposit that into your account, wouldn't that show up as a deposit (which would be either Account Credit or Misc. Credit)? I think our check transactions are more for when you write a check against your account (and need to log the check number). I've never seen a bank statement log a deposited check as a Check transaction with a check number from someone else's checkbook, in my experience.

**Comment by taylerhow** [comment]
Resolved in PR #297
